[package]
name = "common-functions"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../arrow" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../exception" }
common-io = { path = "../io" }

# Github dependencies
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "472f5b6" }

# Crates.io dependencies
base64 = "0.13.0"
blake3 = "1.3.1"
bstr = "0.2.17"
bumpalo = "3.9.1"
bytes = "1.1.0"
crc32fast = "1.3.1"
dyn-clone = "1.0.4"
hex = "0.4.3"
itertools = "0.10.3"
md5 = "0.7.0"
naive-cityhash = "0.2.0"
num = "0.4.0"
num-format = "0.4.0"
num-traits = "0.2.14"
once_cell = "1.9.0"
ordered-float = "2.10.0"
paste = "1.0.6"
rand = { version = "0.8.4", features = ["small_rng"] }
regex = "1.5.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
sha1 = "0.10.0"
sha2 = "0.10.1"
simdutf8 = "0.1.3"
strength_reduce = "0.2.3"
twox-hash = "1.6.2"
uuid = { version = "0.8.2", features = ["v4"] }

[dev-dependencies]
bumpalo = "3.9.1"
common-datablocks = { path = "../datablocks" }
pretty_assertions = "1.1.0"
float-cmp = "0.9.0"
