[package]
name = "common-metrics"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }
common-infallible = { path = "../infallible" }
common-tracing = { path = "../tracing" }

# Crates.io dependencies
once_cell = "1.9.0"
metrics = "0.17.1"
metrics-exporter-prometheus = "0.7.0"
prometheus-parse = "0.2.2"
serde = { version = "1.0.133", features = ["derive"] }
