[package]
name = "common-base"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
# Workspace dependencies
common-tracing = { path = "../tracing" }
common-exception = { path = "../exception" }

# Github dependencies

# Crates.io dependencies
futures = "0.3"
async-trait = "0.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
ctrlc = { version = "3.1.9", features = ["termination"] }
pprof = { version = "0.5", features = ["flamegraph", "protobuf"] }
tokio = { version = "1.12.0", features = ["macros", "rt", "rt-multi-thread", "sync", "fs"] }

[dev-dependencies]
pretty_assertions = "0.7"

