[package]
name = "common-dal"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-base = {path = "../base"}
common-datablocks = {path = "../datablocks"}
common-exception = {path = "../exception"}
common-infallible = {path = "../infallible"}
common-metrics= {path = "../metrics"}

async-compat = "0.2.1"
async-trait = "0.1"
azure_core_mirror = "0.1.0"
azure_storage_mirror = { version = "0.1.0", features = ["blob"] }
bytes = "1"
futures = "0.3"
metrics = "0.17.0"
reqwest = "0.11"
rusoto_core = "0.47.0"
rusoto_s3 = "0.47.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "1.0"
rand = "0.8.4"
tempfile = "3.2.0"

