version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "17:00"
  open-pull-requests-limit: 1
  target-branch: main
  ignore:
  - dependency-name: libc
    versions:
    - 0.2.83
