[package]
name = "common-arrow"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[features]
simd = ["arrow/simd"]

[dependencies] # In alphabetical order
# Workspace dependencies

# Github dependencies
arrow = { package = "arrow2", git="https://github.com/datafuse-extras/arrow2", rev = "95fe10a" }
arrow-flight = { git="https://github.com/datafuse-extras/arrow2", rev = "95fe10a" }

# Crates.io dependencies

[dev-dependencies]
