[package]
name = "common-arrow"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies

# Github dependencies

arrow = { git="https://github.com/apache/arrow-rs", tag = "4.2.0" }
arrow-flight = { git="https://github.com/apache/arrow-rs", tag = "4.2.0" }
parquet = { git="https://github.com/apache/arrow-rs", tag = "4.2.0", features = ["arrow"] }

# Crates.io dependencies

[dev-dependencies]
