[package]
name = "common-arrow"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies

# Github dependencies
arrow = { git = "https://github.com/apache/arrow-rs", rev = "08a662f", features = ["prettyprint"]}
arrow-flight = { git = "https://github.com/apache/arrow-rs", rev = "08a662f"}
parquet = { git = "https://github.com/apache/arrow-rs", rev = "08a662f", features = ["arrow"]}

# Crates.io dependencies

[dev-dependencies]
