[workspace]

members = [
    # Common
    "common/arrow",
    "common/datablocks",
    "common/datavalues",
    "common/flights",
    "common/functions",
    "common/infallible",
    "common/planners",
    "common/progress",
    "common/streams",

    # FuseQuery
    "fusequery/query",

    # FuseStore
    "fusestore/store",
]

[profile.release]
debug = true

[profile.bench]
debug = true
