[workspace]

members = [
    # Common
    "common/datablocks",
    "common/datavalues",
    "common/functions",

    # FuseQuery
    "fusequery/configs",
    "fusequery/query",
    "fusequery/clusters",
    "fusequery/metrics",

    # FuseStore
    "fusestore/store",
]

[profile.release]
debug = true

[profile.bench]
debug = true
