[package]
name = "fuse-engine"
version = "0.1.0"
description = "A Distributed Query Engine"
authors = ["BohuTANG <overred.shuttler@gmail.com>"]
license = "AGPL-3.0"
include = [
    "benches/*.rs",
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2018"

[dependencies]
num = "0.3"
arrow = "2.0.0"
sqlparser = "0.6.1"
thiserror = "1.0.21"
async-trait = "0.1.41"

[dependencies.async-std]
version = "1.7.0"
features = ["unstable", "attributes"]

[dev-dependencies]
criterion = "0.3.3"
pretty_assertions = "0.6.1"

[[bench]]
name = "bench_main"
harness = false

