[workspace]

members = [
    # FuseQuery
    "fusequery/configs",
    "fusequery/query",
    "fusequery/clusters",
    "fusequery/datablocks",
    "fusequery/datavalues",
    "fusequery/metrics",

    # FuseStore
    "fusestore/store",
]

[profile.release]
debug = true

[profile.bench]
debug = true
