[workspace]

members = [
    "query",
    "query/configs",
    "query/datablocks",
    "query/datavalues",
    "query/metrics",
    "store",
]

[profile.release]
debug = true

[profile.bench]
debug = true
