[workspace]

members = [
    # Common
    "common/datablocks",
    "common/datavalues",
    "common/functions",
    "common/infallible",
    "common/planners",

    # FuseQuery
    "fusequery/query",

    # FuseStore
    "fusestore/store",
]

[profile.release]
debug = true

[profile.bench]
debug = true
