[workspace]
members = [
    # Common
    "common/arrow",
    "common/building",
    "common/cache",
    "common/datablocks",
    "common/datavalues",
    "common/store-api-sdk",
    "common/functions",
    "common/metatypes",
    "common/infallible",
    "common/planners",
    "common/progress",
    "common/runtime",
    "common/streams",
    "common/exception",
    "common/tracing",
    "common/profiling",
    "common/store-api",
    "common/sled-store",
    "common/stoppable",
    "common/management",
    "common/io",
    "common/cache",
    "common/uniq_id",
    "common/clickhouse-srv",

    # Query
    "query",

    "metasrv",
    "kvlocal",

    # Store
    "store",

    # SQL Fuzz
    "query/fuzz",

    # CLI
    "cli"
]

[profile.release]
debug = 1
opt-level = "z"     # Optimize for size.
codegen-units = 1   # Reduce number of codegen units to increase optimizations.

[profile.bench]
debug = true

[profile.dev]
split-debuginfo = "unpacked"

