[package]
name = "common-meta-raft-store"
version = "0.1.0"
description = "Raft state machine"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../arrow" }
common-exception = { path = "../../exception" }
common-io = { path = "../../io" }
common-meta-api = { path = "../api" }
common-meta-sled-store = { path = "../sled-store" }
common-meta-types = { path = "../types" }
common-tracing = { path = "../../tracing" }

# github deps
async-raft = { git = "https://github.com/datafuselabs/openraft", tag = "v0.6.2-alpha.14.1" }

# crates.io deps
anyhow = "1.0.51"
async-trait = "0.1.52"
clap = { version = "3.0.0-rc.7", features = ["derive", "env"] }
bytes = "1.1.0"
once_cell = "1.9.0"
derive_more = "0.99.17"
maplit = "1.0.2"
rand = "0.8.4"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
prost = "0.9.0"
thiserror = "1.0.30"
tonic = { version = "0.6.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }

[build-dependencies]
tonic-build = "0.6.2"
common-building = { path = "../../building" }

[dev-dependencies]
common-base = { path = "../../base" }
pretty_assertions = "1.0.0"
tempfile = "3.2.0"
