[package]
name = "common-mem-allocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../base" }
common-infallible = { path = "../infallible" }

parking_lot = "0.12.0"
tikv-jemalloc-sys = "0.4.2"

[dev-dependencies]
common-macros = { path = "../macros" }
