[package]
name = "databend-benchmark"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-infallible = { path = "../../common/infallible" }
common-macros = { path = "../../common/macros" }
common-tracing = { path = "../../common/tracing" }

# Github dependencies
clickhouse-driver = { git = "https://github.com/datafuse-extras/clickhouse_driver", rev = "6e0ecb2" }

# Crates.io dependencies
clap = { version = "3.0.5", features = ["derive", "env"] }
crossbeam-queue = "0.3.2"
ctrlc = { version = "3.2.1", features = ["termination"] }
futures = "0.3.19"
quantiles = "0.7.1"
rand = "0.8.4"
serde = { version = "1.0.133", features = ["derive"] }
