# Usage:
# fuse-query -c fusequery_config_spec.toml

# Log level.
log_level = "INFO"

# FuseQuery rpc address.
# For flight rpc.
rpc_api_address = "127.0.0.1:9090"

# FuseQuery http address.
# For admin RESET API.
http_api_address = "127.0.0.1:8080"

# FuseQuery metrics RESET API.
metric_api_address = "127.0.0.1:7070"

# MySQL Handler.
mysql_handler_host = "127.0.0.1"
mysql_handler_port = 3307

# ClickHouse Handler.
clickhouse_handler_host = "127.0.0.1"
clickhouse_handler_port = 9000