[package]
name = "common-management"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-exception= {path = "../exception"}
common-metatypes= {path = "../metatypes"}
common-store-api= {path = "../store-api"}
common-tracing= {path = "../tracing"}

datafuse-store = {path= "../../store"}

async-trait = "0.1"
tempfile = "3.2.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.8"
sha1 = "0.6.0"

[dev-dependencies]
common-runtime = { path = "../runtime"}
mockall = "0.10.2"
common-metatypes = {path = "../metatypes"}
