name: 'Build Debug'
description: 'Build with debug profile'
inputs:
  github_token:
    description: "Github Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Maximize build space
      uses: ./.github/actions/cleanup

    - uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ inputs.github_token }}

    # Use forked version of action-rs to fix rust-toolchain.toml not supported.
    # Should be removed after https://github.com/actions-rs/toolchain/pull/209 get merged.
    - uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
      with:
        target: ${{ matrix.config.target }}
        default: true
        components: rustfmt, clippy

    # If you need to reset the cache version, increment the number after `v`
    - uses: Swatinem/rust-cache@v1
      with:
        sharedKey: debug-v1

    - uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: ${{ matrix.config.cross }}
        args: --target ${{ matrix.config.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: debug-${{ github.sha }}-${{ matrix.config.os }}-${{ matrix.config.target }}
        path: ./target/${{ matrix.config.target }}/debug/databend-*
