[package]
name = "common-streams"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = {path = "../arrow"}
common-base = {path = "../base" }
common-datablocks = {path = "../datablocks"}
common-datavalues = {path = "../datavalues"}
common-exception = {path = "../exception"}
common-io = {path = "../io"}

# Github dependencies

# Crates.io dependencies
crossbeam = "0.8"
futures = "0.3"
pin-project-lite = "^0.2"
async-trait = "0.1"
async-stream = "0.3.2"
csv-async =  {version = "1.1", features = ["tokio"] }
tokio-stream = { version = "0.1", features = ["net"] }

[dev-dependencies]
pretty_assertions = "1.0"
