name: 'Check'
description: 'Check will do all essential checks'
inputs:
  github_token:
    description: "Github Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Maximize build space
      uses: ./.github/actions/cleanup

    - uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ inputs.github_token }}

    # Use forked version of action-rs to fix rust-toolchain.toml not supported.
    # Should be removed after https://github.com/actions-rs/toolchain/pull/209 get merged.
    - uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
      with:
        default: true
        components: rustfmt, clippy

    # If you need to reset the cache version, increment the number after `v`
    - uses: Swatinem/rust-cache@v1
      with:
        sharedKey: base-v1

    - name: Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --tests -- -D warnings

    - name: Check License Header
      uses: apache/skywalking-eyes@main
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        log: info

    - name: YAML Lint
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: ./
        config_file: .yamllint.yml

    - name: Install cargo-audit
      uses: actions-rs/cargo@v1
      if: "!contains(github.event.head_commit.message, 'skip audit')"
      with:
        command: install
        args: cargo-audit

    - name: Audit dependencies
      uses: actions-rs/cargo@v1
      if: "!contains(github.event.head_commit.message, 'skip audit')"
      with:
        command: audit

    - name: Install cargo-udeps
      uses: actions-rs/cargo@v1
      if: "!contains(github.event.head_commit.message, 'skip udeps')"
      with:
        command: install
        args: cargo-udeps --locked

    - name: Check udeps
      uses: actions-rs/cargo@v1
      if: "!contains(github.event.head_commit.message, 'skip udeps')"
      with:
        command: udeps
        args: --workspace
