[package]
name = "common-contexts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
async-trait = "0.1.52"
opendal = { git = "https://github.com/datafuselabs/opendal", rev = "e882c15" }
time = "0.3.7"
tokio = "1.17"
