apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datafuse.fullname" . }}
  labels:
    {{- include "datafuse.labels" . | nindent 4 }}
data:
  FUSE_QUERY_MYSQL_HANDLER_HOST: "0.0.0.0"
  FUSE_QUERY_CLICKHOUSE_HANDLER_HOST: "0.0.0.0"
  FUSE_QUERY_HTTP_API_ADDRESS: "0.0.0.0:{{ .Values.configs.httpAPIPort }}"
  FUSE_QUERY_METRIC_API_ADDRESS: 0.0.0.0:{{ .Values.configs.metricAPIPort }}
  FUSE_QUERY_RPC_API_ADDRESS: 0.0.0.0:{{ .Values.configs.rpcAPIPort }}
  {{- range $key, $value := .Values.extraEnv}}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
