apiVersion: v1
kind: Service
metadata:
  name: {{ include "datafuse.fullname" . }}
  labels:
    {{- include "datafuse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3307
      targetPort: 3307
      protocol: TCP
      name: mysql
    - port: 7070
      targetPort: 7070
      protocol: TCP
      name: metrics
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: clickhouse
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: rpc
  selector:
    {{- include "datafuse.selectorLabels" . | nindent 4 }}
