apiVersion: v1
kind: Service
metadata:
  name: {{ include "datafuse.fullname" . }}
  labels:
    {{- include "datafuse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3307
      protocol: TCP
      name: mysql
  selector:
    {{- include "datafuse.selectorLabels" . | nindent 4 }}
