# Usage:
# datafuse-query -c datafuse_query_config_spec.toml

[log]
log_level = "ERROR"
log_dir = "./_logs"

# Store
[store]
store_address = ""
store_username = "root"
store_password = "root"

[query]
max_active_sessions = 256

# For flight rpc.
flight_api_address = "0.0.0.0:9092"

# Datafuse Query http address.
# For admin RESET API.
http_api_address = "0.0.0.0:8082"

# Datafuse Query metrics RESET API.
metric_api_address = "0.0.0.0:7072"

# Datafuse Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3308

# Datafuse Query ClickHouse Handler.
clickhouse_handler_host = "0.0.0.0"
clickhouse_handler_port = 9002