[package]
name = "common-ast"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-exception = { path = "../exception" }
common-functions = { path = "../functions" }

# Github dependencies
nom-rule = { git = "https://github.com/andylokandy/nom-rule" }
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "c33837e" }

# Crates.io dependencies
async-trait = "0.1.52"
logos = "0.12"
nom = "7"
nom-supreme = "0.6"
once_cell = "1.9.0"
thiserror = "1.0.30"

[dev-dependencies]
pretty_assertions = "1.0.0"
common-base = { path = "../base" }
