name: 'Test Stateful Standalone'
description: 'Running stateful tests in standalone mode'
inputs:
  profile:
    description: 'The profile for this test'
    required: true
    default: 'debug'
runs:
  using: "composite"
  steps:
    - name: Maximize build space
      uses: ./.github/actions/cleanup

    # Use forked version of action-rs to fix rust-toolchain.toml not supported.
    # Should be removed after https://github.com/actions-rs/toolchain/pull/209 get merged.
    - uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
      with:
        default: true
        target: ${{ matrix.config.target }}

    # If you need to reset the cache version, increment the number after `v`
    - uses: Swatinem/rust-cache@v1
      with:
        sharedKey: stateful-v1

    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.profile }}-${{ github.sha }}-${{ matrix.config.os }}-${{ matrix.config.target }}
        path: ./target/debug

    - name: Set up file as executable
      shell: bash
      run: |
        chmod +x ./target/debug/databend-*

    - name: Minio Setup for (ubuntu-latest only)
      shell: bash
      run: |
        docker run -d -p 9900:9000 --name minio \
                -e "MINIO_ACCESS_KEY=minioadmin" \
                -e "MINIO_SECRET_KEY=minioadmin" \
                -v /tmp/data:/data \
                -v /tmp/config:/root/.minio \
                minio/minio server /data

        export AWS_ACCESS_KEY_ID=minioadmin
        export AWS_SECRET_ACCESS_KEY=minioadmin
        export AWS_EC2_METADATA_DISABLED=true
        aws --endpoint-url http://127.0.0.1:9900/ s3 mb s3://testbucket
        aws --endpoint-url http://127.0.0.1:9900/ s3 cp tests/data s3://testbucket/tests/data  --recursive

    - name: Run Stateless Tests with Standalone mode (ubuntu-latest only)
      shell: bash
      run: |
        bash ./scripts/ci/ci-run-stateful-tests-standalone-s3.sh
