[package]
name = "common-datavalues"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Github dependencies
arrow = { git = "https://github.com/apache/arrow", rev="46161d2" }

# Crates.io dependencies
anyhow = "1.0.40"
paste = "^1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "0.7"
