[package]
name = "common-mem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jemalloc-sys = { version = "0.3.2" }
common-infallible = { path = "../infallible" }
parking_lot = "0.11"
common-mem-derive = { path = "../mem-derive" }