[package]
name = "common-naive-cityhash"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
edition = "2021"
license = "Apache-2.0"
description = "A naive 128bits cityhash v102 implementation for clickhouse-srv."

[lib]
doctest = false
test = false

[dependencies]
