name: "CI Environment Setup"
description: |
  Setup a common environment for CI jobs.

runs:
  using: "composite"
  steps:
    - name: Install common dependencies
      shell: bash
      run: scripts/dev_setup.sh -t -o -b -p -y -s
