[package]
name = "common-tracing"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
once_cell = "1.9.0"
opentelemetry = { version = "0.16.0", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.15.0", features = ["rt-tokio"] }
tonic = "0.6.2"
tracing = "0.1.29"
tracing-appender = "0.2.0"
tracing-bunyan-formatter = "0.3.1"
tracing-futures = {version ="0.2.5", features = ["futures-03"]}
tracing-opentelemetry = "0.16.0"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
