[package]
name = "common-planners"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies
common-datavalues = {path = "../datavalues"}
common-functions = {path = "../functions"}

# github dependencies

# Crates.io dependencies
anyhow = "1.0.40"
dyn-clone = "1.0.4"
indexmap = "1.6.1"
lazy_static = "1.4.0"
paste = "^1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "0.7"
