[package]
name = "common-dal2"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../exception" }

async-compat = "0.2.1"
async-trait = "0.1.52"
bytes = "1.1.0"
futures = "0.3.19"
reqwest = "0.11.7"
rusoto_core = "0.47.0"
rusoto_s3 = "0.47.0"
rusoto_credential = "0.47.0"
tokio = {version="1.15.0",features=["fs"]}
