on: [push, pull_request]
name: FuseQuery Daily

env:
  CARGO_TERM_COLOR: always

jobs:
  daily:
    name: Daily jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup devtool
        run: scripts/dev_setup.sh -t -o -b -p -y -s

      - name: Code coverage
        run: make coverage

      - name: Push coverage report to S3
        run: |
          set -x
          SECRET_ID="${{ secrets.CI_TENCENT_COS_ID }}"
          SECRET_KEY="${{ secrets.CI_TENCENT_COS_KEY}}"
          BUCKET="${{ secrets.CI_TENCENT_COS_BUCKET }}"
          REGION="${{ secrets.CI_TENCENT_COS_REGION}}"
          SUFFIX="$(date +"%Y-%m-%d")-$(git rev-parse --short=8 HEAD)"
          #Push grcov
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
          coscmd upload -r ./target/debug/coverage/ coverage/SUFFIX
          coscmd upload -r ./target/debug/coverage/ coverage/latest
