on: [push, pull_request]
name: FuseQuery Unit Tests

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Unit tests, code coverage(disabled)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install common dependencies
        shell: bash
        run: scripts/dev_setup.sh -t -o -b -p -y -s

      - uses: actions-rs/cargo@v1
        with:
          command: clean

      - uses: actions-rs/cargo@v1
        with:
          command: test
          components: rustfmt
          args: --all-features --no-fail-fast
