on: [push, pull_request]
name: FuseQuery Unit Tests

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Unit tests and code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install common dependencies
        shell: bash
        run: make setup

      - uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: Coverage
        shell: bash
        run: make coverage

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/debug/lcov.info

      - name: Install coscmd
        run: sudo pip install coscmd
      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.CI_TENCENT_COS_ID }}
          SECRET_KEY: ${{ secrets.CI_TENCENT_COS_KEY }}
          BUCKET: ${{ secrets.CI_TENCENT_COS_BUCKET }}
          REGION: ${{ secrets.CI_TENCENT_COS_REGION }}}
        run: #coscmd config -a ${SECRET_ID} -s ${SECRET_KEY} -b ${BUCKET} -r ${REGION}

      - name: Upload to COS
        run: |
          SUFFIX="$(date +"%Y-%m-%d")-$(git rev-parse --short=8 HEAD)"
          genhtml -o ./target/debug/coverage/ --show-details --highlight --ignore-errors source --legend ./target/debug/lcov.info
          #coscmd upload -r ./target/debug/coverage/ coverage/${SUFFIX}
          #coscmd upload -r ./target/debug/coverage/ coverage/latest
