name: Performance Tests(Standalone)
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt
          override: true

      - name: Build Release
        run: RUST_BACKTRACE=full RUSTFLAGS="-C target-cpu=native" cargo build --bin=fuse-query --release

      - name: Run Performance Tests with Standalone mode
        run: |
          bash ./scripts/ci/ci-performance-tests-standalone.sh
