name: Platform

on:
  push:
    branches:
      - main
    paths:
      - "rust-toolchain.toml"
      - "scripts/setup/dev_setup.sh"

jobs:
  build_dev_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian
          - alpine
    steps:
      - uses: actions/checkout@v2

      - name: Maximize build space
        uses: ./.github/actions/cleanup

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get rust toolchain version
        id: toolchain_version
        run: |
          version=$(awk -F'[ ="]+' '$1 == "channel" { print $2 }' rust-toolchain.toml)
          echo "::set-output name=RUST_TOOLCHAIN::${version}"

      - name: Build and publish databend build tool image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/build-tool:${{ matrix.distro }}, ${{ secrets.DOCKERHUB_NAMESPACE }}/build-tool:${{ matrix.distro }}-${{ steps.toolchain_version.outputs.RUST_TOOLCHAIN }}
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./docker/build-tool/${{ matrix.distro }}/Dockerfile
