name: Stateless Tests
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release
      - name: Run Tests
        run: |
          echo "Starting fues-query"
          nohup target/release/fuse-query --log-level ERROR&
          sleep 3
          echo "Starting fuse-test"
          cd tests
          ./fuse-test
